{"variants":[{"paths":["\/documentation\/headlesssdk"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/headlesssdk"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK","interfaceLanguage":"swift"},"topicSections":[{"title":"Articles","identifiers":["doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/HeadlessSDK"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/EmbeddedWalletProvider","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/Privy","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletConnector","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletCreator","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletRecoverer"]},{"title":"Protocols","identifiers":["doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/Chainable"]},{"title":"Structures","identifiers":["doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/AuthResponse","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/BlockExplorer","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/BlockExplorers","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/Chain","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/Contracts","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/CustomAuth","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/JWT","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/Multicall3","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/NativeCurrency","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/PrivyConfig","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/RpcRequest","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/RpcUrl","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/RpcUrls","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/User","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/Wallet","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletConnectResponseData","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletCreateResponseData","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletRecoverRequest","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletRecoverResponseData","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletRpcResponseData","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletSetPasswordResponseData"]},{"title":"Functions","identifiers":["doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/hexStringToInt(_:)","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/toHexString(_:)"]},{"title":"Enumerations","identifiers":["doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/AuthState","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/EmbeddedWalletState","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/LinkedAccount","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/PrivyEmbeddedWalletError","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/PrivyError","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/SupportedChain"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"HeadlessSDK","title":"HeadlessSDK","symbolKind":"module","role":"collection","modules":[{"name":"HeadlessSDK"}]},"hierarchy":{"paths":[[]]},"references":{"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK":{"role":"collection","title":"HeadlessSDK","abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK","kind":"symbol","type":"topic","url":"\/documentation\/headlesssdk"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/hexStringToInt(_:)":{"role":"symbol","title":"hexStringToInt(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hexStringToInt"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/hexStringToInt(_:)","kind":"symbol","type":"topic","url":"\/documentation\/headlesssdk\/hexstringtoint(_:)"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/BlockExplorer":{"role":"symbol","title":"BlockExplorer","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlockExplorer"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/BlockExplorer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BlockExplorer"}],"url":"\/documentation\/headlesssdk\/blockexplorer"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/WalletCreator":{"role":"symbol","title":"WalletCreator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WalletCreator"}],"abstract":[{"type":"text","text":"Handles wallet creation after user authentication"}],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletCreator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WalletCreator"}],"url":"\/documentation\/headlesssdk\/walletcreator"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/User":{"role":"symbol","title":"User","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"User"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/User","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"User"}],"url":"\/documentation\/headlesssdk\/user"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/WalletConnectResponseData":{"role":"symbol","title":"WalletConnectResponseData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"WalletConnectResponseData"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletConnectResponseData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WalletConnectResponseData"}],"url":"\/documentation\/headlesssdk\/walletconnectresponsedata"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/RpcRequest":{"role":"symbol","title":"RpcRequest","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RpcRequest"}],"abstract":[{"type":"text","text":"Request made on behalf of the embedded wallet for the logged in user"}],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/RpcRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RpcRequest"}],"url":"\/documentation\/headlesssdk\/rpcrequest"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/WalletCreateResponseData":{"role":"symbol","title":"WalletCreateResponseData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"WalletCreateResponseData"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletCreateResponseData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WalletCreateResponseData"}],"url":"\/documentation\/headlesssdk\/walletcreateresponsedata"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/EmbeddedWalletState":{"role":"symbol","title":"EmbeddedWalletState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmbeddedWalletState"}],"abstract":[{"type":"text","text":"The different states of the embedded wallet"}],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/EmbeddedWalletState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmbeddedWalletState"}],"url":"\/documentation\/headlesssdk\/embeddedwalletstate"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/WalletSetPasswordResponseData":{"role":"symbol","title":"WalletSetPasswordResponseData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"WalletSetPasswordResponseData"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletSetPasswordResponseData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WalletSetPasswordResponseData"}],"url":"\/documentation\/headlesssdk\/walletsetpasswordresponsedata"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/WalletRpcResponseData":{"role":"symbol","title":"WalletRpcResponseData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"WalletRpcResponseData"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletRpcResponseData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WalletRpcResponseData"}],"url":"\/documentation\/headlesssdk\/walletrpcresponsedata"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/Chain":{"role":"symbol","title":"Chain","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chain"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/Chain","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Chain"}],"url":"\/documentation\/headlesssdk\/chain"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/SupportedChain":{"role":"symbol","title":"SupportedChain","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupportedChain"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/SupportedChain","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SupportedChain"}],"url":"\/documentation\/headlesssdk\/supportedchain"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/PrivyConfig":{"role":"symbol","title":"PrivyConfig","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrivyConfig"}],"abstract":[{"type":"text","text":"Configuration for your application’s privy client instance"}],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/PrivyConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PrivyConfig"}],"url":"\/documentation\/headlesssdk\/privyconfig"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/HeadlessSDKVersionNumber":{"role":"symbol","title":"HeadlessSDKVersionNumber","fragments":[{"kind":"identifier","text":"HeadlessSDKVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for HeadlessSDK."}],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/HeadlessSDKVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/headlesssdk\/headlesssdkversionnumber"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/Multicall3":{"role":"symbol","title":"Multicall3","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Multicall3"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/Multicall3","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Multicall3"}],"url":"\/documentation\/headlesssdk\/multicall3"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/PrivyEmbeddedWalletError":{"role":"symbol","title":"PrivyEmbeddedWalletError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrivyEmbeddedWalletError"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/PrivyEmbeddedWalletError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PrivyEmbeddedWalletError"}],"url":"\/documentation\/headlesssdk\/privyembeddedwalleterror"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/AuthState":{"role":"symbol","title":"AuthState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthState"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/AuthState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthState"}],"url":"\/documentation\/headlesssdk\/authstate"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/PrivyError":{"role":"symbol","title":"PrivyError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PrivyError"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/PrivyError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PrivyError"}],"url":"\/documentation\/headlesssdk\/privyerror"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/Chainable":{"role":"symbol","title":"Chainable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chainable"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/Chainable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Chainable"}],"url":"\/documentation\/headlesssdk\/chainable"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/LinkedAccount":{"role":"symbol","title":"LinkedAccount","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LinkedAccount"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/LinkedAccount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LinkedAccount"}],"url":"\/documentation\/headlesssdk\/linkedaccount"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/Contracts":{"role":"symbol","title":"Contracts","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Contracts"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/Contracts","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Contracts"}],"url":"\/documentation\/headlesssdk\/contracts"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/RpcUrl":{"role":"symbol","title":"RpcUrl","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RpcUrl"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/RpcUrl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RpcUrl"}],"url":"\/documentation\/headlesssdk\/rpcurl"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/EmbeddedWalletProvider":{"role":"symbol","title":"EmbeddedWalletProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmbeddedWalletProvider"}],"abstract":[{"type":"text","text":"Represents the current connection state and available functionality for the user’s Privy embedded wallet associated with the current application"}],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/EmbeddedWalletProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EmbeddedWalletProvider"}],"url":"\/documentation\/headlesssdk\/embeddedwalletprovider"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/NativeCurrency":{"role":"symbol","title":"NativeCurrency","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NativeCurrency"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/NativeCurrency","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NativeCurrency"}],"url":"\/documentation\/headlesssdk\/nativecurrency"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/Privy":{"role":"symbol","title":"Privy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Privy"}],"abstract":[{"type":"text","text":"The Privy SDK Main Class."},{"type":"text","text":" "},{"type":"text","text":"Create an instance with your config to interact with privy"}],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/Privy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Privy"}],"url":"\/documentation\/headlesssdk\/privy"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/CustomAuth":{"role":"symbol","title":"CustomAuth","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomAuth"}],"abstract":[{"type":"text","text":"Account created with an alternative auth provider "},{"type":"emphasis","inlineContent":[{"type":"text","text":"(Auth0 etc…)"}]}],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/CustomAuth","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CustomAuth"}],"url":"\/documentation\/headlesssdk\/customauth"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/JWT":{"role":"symbol","title":"JWT","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWT"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/JWT","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JWT"}],"url":"\/documentation\/headlesssdk\/jwt"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/toHexString(_:)":{"role":"symbol","title":"toHexString(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toHexString"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Convert a value to a hex string, supports Int or String argument"}],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/toHexString(_:)","kind":"symbol","type":"topic","url":"\/documentation\/headlesssdk\/tohexstring(_:)"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/Wallet":{"role":"symbol","title":"Wallet","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wallet"}],"abstract":[{"type":"text","text":"Self custodial embedded wallet account "},{"type":"emphasis","inlineContent":[{"type":"text","text":"(created by Privy)"}]}],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/Wallet","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Wallet"}],"url":"\/documentation\/headlesssdk\/wallet"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/AuthResponse":{"role":"symbol","title":"AuthResponse","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthResponse"}],"abstract":[{"type":"text","text":"The user object representing an authenticated user"}],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/AuthResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthResponse"}],"url":"\/documentation\/headlesssdk\/authresponse"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/WalletRecoverRequest":{"role":"symbol","title":"WalletRecoverRequest","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"WalletRecoverRequest"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletRecoverRequest","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WalletRecoverRequest"}],"url":"\/documentation\/headlesssdk\/walletrecoverrequest"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/RpcUrls":{"role":"symbol","title":"RpcUrls","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RpcUrls"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/RpcUrls","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RpcUrls"}],"url":"\/documentation\/headlesssdk\/rpcurls"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/WalletRecoverResponseData":{"role":"symbol","title":"WalletRecoverResponseData","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"WalletRecoverResponseData"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletRecoverResponseData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WalletRecoverResponseData"}],"url":"\/documentation\/headlesssdk\/walletrecoverresponsedata"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/WalletConnector":{"role":"symbol","title":"WalletConnector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WalletConnector"}],"abstract":[{"type":"text","text":"Handles wallet creation after user authentication"}],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletConnector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WalletConnector"}],"url":"\/documentation\/headlesssdk\/walletconnector"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/BlockExplorers":{"role":"symbol","title":"BlockExplorers","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlockExplorers"}],"abstract":[],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/BlockExplorers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BlockExplorers"}],"url":"\/documentation\/headlesssdk\/blockexplorers"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/WalletRecoverer":{"role":"symbol","title":"WalletRecoverer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WalletRecoverer"}],"abstract":[{"type":"text","text":"Handles wallet recovery"}],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/WalletRecoverer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WalletRecoverer"}],"url":"\/documentation\/headlesssdk\/walletrecoverer"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/HeadlessSDKVersionString":{"role":"symbol","title":"HeadlessSDKVersionString","fragments":[{"kind":"identifier","text":"HeadlessSDKVersionString"}],"abstract":[{"type":"text","text":"Project version string for HeadlessSDK."}],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/HeadlessSDKVersionString","kind":"symbol","type":"topic","url":"\/documentation\/headlesssdk\/headlesssdkversionstring"},"doc://io.privy.HeadlessSDK/documentation/HeadlessSDK/HeadlessSDK":{"role":"article","title":"`privy-ios`","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"privy-ios"},{"type":"text","text":" SDK is an pure swift interface for working with Privy.io in an iOS app. It is "},{"type":"codeVoice","code":"headless"},{"type":"text","text":" meaning that you bring your own UI, while leveraging powerful auth and embedded wallet features from Privy 🪄!"}],"identifier":"doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/HeadlessSDK","kind":"article","type":"topic","url":"\/documentation\/headlesssdk\/headlesssdk"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Articles","identifiers":["doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/HeadlessSDK"],"generated":true},{"title":"Variables","identifiers":["doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/HeadlessSDKVersionNumber","doc:\/\/io.privy.HeadlessSDK\/documentation\/HeadlessSDK\/HeadlessSDKVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}